aws:
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY:dummy}
  secret-key: ${AWS_SECRET_KEY:dummy}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}